language: php

php:
  - 7.1
  - 7.2
  - hhvm

before_install:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/coveralls